### PR TITLE
use "mvn.cmd" instead of "mvn" command on Windows. fixes #24

### LINKED ISSUE #24: Cannot run mvn command with ProcessBuilder on Windows
## Description
When I run `java -Dpaperclip.install=true -jar paperclip.jar` :
```
$ java -Dpaperclip.install=true -jar paperclip.jar
Maven must be installed and on your PATH.
java.io.IOException: Cannot run program "mvn": CreateProcess error=2, Le fichier spécifié est introuvable
        at java.lang.ProcessBuilder.start(Unknown Source)
        at io.papermc.paperclip.Paperclip.mavenInstall(Paperclip.java:260)
        at io.papermc.paperclip.Paperclip.setupEnv(Paperclip.java:103)
        at io.papermc.paperclip.Paperclip.main(Paperclip.java:48)
Caused by: java.io.IOException: CreateProcess error=2, Le fichier spécifié est introuvable
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 4 more
```
It seems to be a problem with java + Windows.

This guy got the same issue :
https://stackoverflow.com/questions/7966194/running-mvn-using-processbuilder

When I tried to test `new ProcessBuilder("mvn.cmd", "-version").start()`, it worked perfectly. So if `mvn.cmd` can be automatically used instead of `mvn` for windows users, it would fix the thing I think.

Thank you in advance ! :D

## Additional Information
System path is correctly set for the maven bin so I can run `mvn -version` in console without any issues.

## System information
Java : jdk 1.8_0_201
OS : Windows 10 version 19041.450
16Go RAM, x64

### PR DESCRIPTION
**Pull request by jmanpenilla**
Fixes #24 (``java -jar -Dpaperclip.install=true paperclip.jar`` not working on Windows)

Checks for Windows OS using the "os.name" System property.
https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html

Tested working on Windows 10 (and still working on Linux)

### CODE REVIEW

File: java8/src/main/java/io/papermc/paperclip/Paperclip.java [hunk 1]
```diff
@@ -256,8 +256,10 @@ private static Path extractPom(Path paperJar) throws IOException {
     }
 
     private static void mavenInstall(Path paperJar) {
+        // On Windows we need to use "mvn.cmd" instead of "mvn"
+        final String mavenCommand = System.getProperty("file.separator").contains("\\") ? "mvn.cmd" : "mvn";
```
Comment (Proximyst) [inline java8/src/main/java/io/papermc/paperclip/Paperclip.java:260]: Use the property `os.name`

**Review by Proximyst — CHANGES_REQUESTED** [review]

File: java8/src/main/java/io/papermc/paperclip/Paperclip.java (hunk 1 above)
Comment (jmanpenilla) [reply java8/src/main/java/io/papermc/paperclip/Paperclip.java]: ok, updated

**Review by Proximyst — APPROVED** [review]

File: java8/src/main/java/io/papermc/paperclip/Paperclip.java [hunk 2]
```diff
@@ -256,8 +256,10 @@ private static Path extractPom(Path paperJar) throws IOException {
     }
 
     private static void mavenInstall(Path paperJar) {
+        // On Windows we need to use "mvn.cmd" instead of "mvn"
+        final String mavenCommand = System.getProperty("os.name").toLowerCase().contains("windows") ? "mvn.cmd" : "mvn";
```
Comment (kashike) [inline java8/src/main/java/io/papermc/paperclip/Paperclip.java:260]:
```suggestion
        final String mavenCommand = System.getProperty("os.name").toLowerCase(java.util.Locale.ENGLISH).contains("windows") ? "mvn.cmd" : "mvn";
```
Import the class.

**Review by kashike — CHANGES_REQUESTED** [review]

**Review by kashike — APPROVED** [review]
